
language: php

notifications:
  email:
    recipients:
    - mattp@catalyst-au.net

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6

env:
 matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE ESVER=2.3.4
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE ESVER=2.4.4
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE ESVER=2.3.4
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE ESVER=2.4.4
  - DB=pgsql MOODLE_BRANCH=master ESVER=2.3.4
  - DB=pgsql MOODLE_BRANCH=master ESVER=2.4.4
  - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE ESVER=2.3.4
  - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE ESVER=2.4.4
  - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE ESVER=2.3.4
  - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE ESVER=2.4.4
  - DB=mysqli MOODLE_BRANCH=master ESVER=2.3.4
  - DB=mysqli MOODLE_BRANCH=master ESVER=2.4.4

matrix:
  include:
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=master
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=master

before_install:
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/${ESVER}/elasticsearch-${ESVER}.deb && dpkg -i --force-confnew elasticsearch-${ESVER}.deb && service elasticsearch restart

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
# - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci csslint    # No CSS
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint     # No JS
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat      # No tests yet

